// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ARVis.Flatbuffers
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Intrinsics : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Intrinsics GetRootAsIntrinsics(ByteBuffer _bb) { return GetRootAsIntrinsics(_bb, new Intrinsics()); }
  public static Intrinsics GetRootAsIntrinsics(ByteBuffer _bb, Intrinsics obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Intrinsics __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ARVis.Flatbuffers.Vec2? Focallength { get { int o = __p.__offset(4); return o != 0 ? (ARVis.Flatbuffers.Vec2?)(new ARVis.Flatbuffers.Vec2()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public ARVis.Flatbuffers.Vec2? Principalpoint { get { int o = __p.__offset(6); return o != 0 ? (ARVis.Flatbuffers.Vec2?)(new ARVis.Flatbuffers.Vec2()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public ARVis.Flatbuffers.Vec2Int? Resolution { get { int o = __p.__offset(8); return o != 0 ? (ARVis.Flatbuffers.Vec2Int?)(new ARVis.Flatbuffers.Vec2Int()).__assign(o + __p.bb_pos, __p.bb) : null; } }
  public float Skew { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static void StartIntrinsics(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddFocallength(FlatBufferBuilder builder, Offset<ARVis.Flatbuffers.Vec2> focallengthOffset) { builder.AddStruct(0, focallengthOffset.Value, 0); }
  public static void AddPrincipalpoint(FlatBufferBuilder builder, Offset<ARVis.Flatbuffers.Vec2> principalpointOffset) { builder.AddStruct(1, principalpointOffset.Value, 0); }
  public static void AddResolution(FlatBufferBuilder builder, Offset<ARVis.Flatbuffers.Vec2Int> resolutionOffset) { builder.AddStruct(2, resolutionOffset.Value, 0); }
  public static void AddSkew(FlatBufferBuilder builder, float skew) { builder.AddFloat(3, skew, 0.0f); }
  public static Offset<ARVis.Flatbuffers.Intrinsics> EndIntrinsics(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<ARVis.Flatbuffers.Intrinsics>(o);
  }
}


static public class IntrinsicsVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Focallength*/, 8 /*ARVis.Flatbuffers.Vec2*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Principalpoint*/, 8 /*ARVis.Flatbuffers.Vec2*/, 4, false)
      && verifier.VerifyField(tablePos, 8 /*Resolution*/, 4 /*ARVis.Flatbuffers.Vec2Int*/, 2, false)
      && verifier.VerifyField(tablePos, 10 /*Skew*/, 4 /*float*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
