// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace ARVis.Flatbuffers
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Vec2Int : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p = new Struct(_i, _bb); }
  public Vec2Int __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public short X { get { return __p.bb.GetShort(__p.bb_pos + 0); } }
  public short Y { get { return __p.bb.GetShort(__p.bb_pos + 2); } }

  public static Offset<ARVis.Flatbuffers.Vec2Int> CreateVec2Int(FlatBufferBuilder builder, short X, short Y) {
    builder.Prep(2, 4);
    builder.PutShort(Y);
    builder.PutShort(X);
    return new Offset<ARVis.Flatbuffers.Vec2Int>(builder.Offset);
  }
}


}
