# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Flatbuffers

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Vec2Int(object):
    __slots__ = ['_tab']

    @classmethod
    def SizeOf(cls):
        return 4

    # Vec2Int
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Vec2Int
    def X(self): return self._tab.Get(flatbuffers.number_types.Int16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(0))
    # Vec2Int
    def Y(self): return self._tab.Get(flatbuffers.number_types.Int16Flags, self._tab.Pos + flatbuffers.number_types.UOffsetTFlags.py_type(2))

def CreateVec2Int(builder, x, y):
    builder.Prep(2, 4)
    builder.PrependInt16(y)
    builder.PrependInt16(x)
    return builder.Offset()
